music.jumpDown.play()
scene.setBackgroundImage(assets.image`myImage2`)
game.showLongText("A humble carpenter has been working for years so that he could create something unique,something that will amaze the world. ", DialogLayout.Bottom)
game.showLongText("His masterpiece was a table made with the best quality wood. ", DialogLayout.Bottom)
game.showLongText("Once he finished his masterpiece, the table started fleeing from home, something that annoyed toa high extent the carpenter. ", DialogLayout.Bottom)
game.showLongText("For this reason, he will hunt the table ", DialogLayout.Bottom)
game.showLongText("FOREVER", DialogLayout.Bottom)
forever(function () {
    music.playMelody("E B C5 A B G A F ", 77)
})
